name: Deploy to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write

    env:
      # Translated languages other than Japanese
      LANGUAGES: en

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Gettext
        run: |
          sudo apt update
          sudo apt install gettext

      - name: Install dependencies
        run: |
          cargo install \
            mdbook@0.4.40 \
            mdbook-toc@0.14.2 \
            mdbook-callouts@0.2.1 \
            mdbook-codename@0.0.1 \
            mdbook-mermaid@0.14.0 \
            mdbook-i18n-helpers@0.3.6

      - name: Build book for Japanese
        run: |
          scripts/build.sh ja book

      - name: Build book for other languages
        run: |
          for lang in $LANGUAGES; do
            scripts/build.sh $lang book/$lang
          done

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'writing-hypervisor-in-zig'
          directory: 'book'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          wranglerVersion: '3'
